id = "monokai-nebula"
name = "Monokai Nebula"
version = "0.2.1"
schema_version = 1
authors = ["Jake Callahan <jacob.callahan05@gmail.com>"]
repository = "https://github.com/jacobcallahan/monokai-nebula-zed"
description = "A deep and vivid Monokai-inspired theme for the Zed editor"
