name: JSON Schema Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run pre-commit checks
        run: |
          uvx pre-commit run --all-files
