name: JSON Schema Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run pre-commit checks
        run: |
          uvx pre-commit run --all-files

      - name: Checkout zed repo
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          path: zed

      - name: Install mold linker
        run: |
          sudo apt-get update
          sudo apt-get install -y mold

      - name: Create scratch_dir
        run: mkdir -p "${{ runner.temp }}/zed-theme-scratch"

      - name: Run zed-extension
        run: |
          cargo run -p extension_cli -- --source-dir $GITHUB_WORKSPACE --output-dir "${{ runner.temp }}/zed-theme-out" --scratch-dir "${{ runner.temp }}/zed-theme-scratch"
        working-directory: ./zed
