name: JSON Schema Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run pre-commit checks
        run: |
          uvx pre-commit run --all-files

      - name: Checkout zed repo
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          path: zed

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install mold linker
        run: |
          sudo apt-get update
          sudo apt-get install -y mold

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./zed/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('zed/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Create scratch_dir
        run: mkdir -p "${{ runner.temp }}/zed-theme-scratch"

      - name: Run zed-extension
        run: |
          cargo run -p extension_cli -- --source-dir $GITHUB_WORKSPACE --output-dir "${{ runner.temp }}/zed-theme-out" --scratch-dir "${{ runner.temp }}/zed-theme-scratch"
        working-directory: ./zed
